### PR TITLE
Document update for Configuring EnvVars in Configs box

### PR DESCRIPTION
**Pull request by mupasak**
This PR updates the document to give an example of configuring environment variables in the Configs box while creating an app.

### CODE REVIEW

**Comment by mupasak** [comment]
@gainsley could you review it once?

**Comment by gainsley** [comment]
@levshvarts can you review? Thanks.

**Review by levshvarts — APPROVED** [review]
Looks good. Thanks.

**Comment by mupasak** [comment]
Could we merge it?

**Comment by gainsley** [comment]
Sorry, forgot to merge this.

**Pull request merged**
